### PR TITLE
Initial Impl of Session Logic

### LINKED ISSUE #7: Implement session logic and configure DB
- [ ] Session Logic:
- Open and persist a connection to ESS (will probably need reconnection logic outside of what PlanetsideApi provides out of the box, since the websockets and subscriptions can be finicky...)
- Subscribe to all character events (may downgrade to only SaCa members depending on DB storage)
- Build sessions structs over time, starting with a `PlayerLogin` event, and ending with `PlayerLogout`.
- After a `PlayerLogout`, store the session the DB

- [ ] Will need an API to:
- Search for a session
- narrow result(s) of a search by active or closed sessions
- search by a field other than `character_id` (i.e. their name)

### PR DESCRIPTION
**Pull request by Bentheburrito**
Here is an initial impl of session tracking/storage - I've mostly ported CAIData's logic and cleaned it up a lot.

Archiving sessions will likely need a rework, since in my testing it wasn't exactly reliable (though this is due to the Census's unpredictable updates after a logout.) However, it's a start, and you'll have some data to work with on the front end, and worse case we don't find a reliable way to get session shots/hits and drop those fields.

Close #7

### CODE REVIEW

**Review by dm0896665 — APPROVED** [review]
Looks good to me, you may have done it, but if not would you think it would be a good idea to make endpoints out of our data fetches that we can hit? Just so we could also make an API out of it as well basically. Could also make it easier to implement into the front it to. Not sure how hard it would be to just convert the fetches by endpoints if you haven't, but just a thought.

**Comment by Bentheburrito** [comment]
I think we could definitely make an API, though for the front end specifically, we can call things directly is most cases (we can access everything in `sacastats` from `sacastats_web`, and there's a phoenix JS module, too.) We may need to make endpoints for back end things at some point (like giving other folks programmatic access to sessions,) but for the front end I don't think it'll be necessary.

**Comment by dm0896665** [comment]
Okay, I am about ready to start adding more code to this thing again lol. Is there a certain way to get most of the character info from the API right now? I was thinking of starting with creating the pages out for those

**Comment by Bentheburrito** [comment]
Eyyy, yes! I will put some code/queries in the discord channel to keep this thread less cluttered.
Also, since we're the only two working on this, you can merge PRs after you approve them :)

**Pull request merged**
