### PR TITLE
Update image defaults

### LINKED ISSUE #85: Unknown Weapons
Edit the `get_weapons.exs` script so that it keeps the original `image_path` even if that path doesn't exist yet. 

This will allow the `onerror` to take over and show the unknown vehicle/infantry weapon instead of a question mark. It will also let the website stay more up-to-date by getting the proper image as it gets added by daybreak instead of needing to rerun the script constantly to get the images updated.

### PR DESCRIPTION
**Pull request by Bentheburrito**
Closes #85

### CODE REVIEW

**Review by dm0896665 — CHANGES_REQUESTED** [review]
Would you be able to run that new script? I tried to do it earlier, but it said I was missing the QueryBuilder dependency, but it was right there in the imports so I'm not sure what went wrong.

**Comment by Bentheburrito** [comment]
Can you post the error? It works for me. Might want to run `mix deps.get` again.

**Comment by dm0896665** [comment]
`** (CompileError) get_weapons.exs:10: module PS2.API.QueryBuilder is not loaded and could not be found
    (elixir 1.12.1) lib/code.ex:1261: Code.require_file/2`

**Comment by Bentheburrito** [comment]
How are you running it? I did `mix run ./lib/sacastats/scripts/get_weapons.exs`

**Comment by dm0896665** [comment]
Ah okay, that works! I tried going to the scripts folder and running `iex get_weapons.exs`

**Comment by Bentheburrito** [comment]
ahh okay nice. I should've mentioned we need to run it with `mix` so all of our dependencies are loaded before the script starts

**Pull request merged**
