### PR TITLE
Codebase Cleanup pass (CharacterController)

### PR DESCRIPTION
**Pull request by Bentheburrito**
I moved all the helper fns in CharacterControllers to new helper/context modules, `SacaStats.{Characters, Conversions, Weapons}` and optimized some of them (lmk if you have questions!). I made a bunch of other changes, like consolidating our two `maybe_to_int` fns into one under `Utils`.

### To Test
Visit all pages (especially the character ones), make sure all content looks correct

### CODE REVIEW

**Comment by dm0896665** [comment]
Nice consolidation! But I do have a question about [weapons_not_found.html.heex](https://github.com/Bentheburrito/sacastats/pull/126/files#diff-7a95ae29da0e0a4ddb793a6868d315b9d268bcfa4b9e313b3c568fcc2ee4d5d1). When would this end up being used? I am just wondering because we do have unknown weapon images that we could use.

**Comment by Bentheburrito** [comment]
> Nice consolidation! But I do have a question about [weapons_not_found.html.heex](https://github.com/Bentheburrito/sacastats/pull/126/files#diff-7a95ae29da0e0a4ddb793a6868d315b9d268bcfa4b9e313b3c568fcc2ee4d5d1). When would this end up being used? I am just wondering because we do have unknown weapon images that we could use.

Good question - I thought about having an error page that displays when loading the weapon stats failed for some reason (e.g. Census is down and we don't have it cached). I just made that page on a whim, so since it doesn't really belong in this PR (and doesn't actually have any content), I can create an actual issue for it. Thanks for asking!

**Comment by dm0896665** [comment]
Ah, okay, that makes sense.

**Review by dm0896665 — APPROVED** [review]
Looking good!

**Pull request merged**
